language: c

# Build options
script:
    - git clone https://github.com/yyang42/moulitest $HOME/moulitest
    - echo "LIBFT_PATH=$TRAVIS_BUILD_DIR" >> $HOME/moulitest/config.ini
    - cd $HOME/moulitest && make libft_bonus

# Builds
os:
    - osx
    - linux

compiler:
    - gcc
    - clang
